create table if not exists public.fish_game_record (
  id bigint generated by default as identity primary key,
  player_name text not null check (char_length(player_name) between 1 and 14),
  score integer not null check (score >= 0 and score <= 100000000),
  level integer not null default 1 check (level >= 1 and level <= 1000),
  created_at timestamptz not null default now()
);

alter table public.fish_game_record enable row level security;

grant select, insert on public.fish_game_record to anon;
grant usage on sequence public.fish_game_record_id_seq to anon;

drop policy if exists "fish_game_record_select_top_scores" on public.fish_game_record;
drop policy if exists "fish_game_record_insert_scores" on public.fish_game_record;

create policy "fish_game_record_select_top_scores"
on public.fish_game_record
for select
to anon
using (true);

create policy "fish_game_record_insert_scores"
on public.fish_game_record
for insert
to anon
with check (
  char_length(player_name) between 1 and 14
  and score >= 0
  and score <= 100000000
  and level >= 1
  and level <= 1000
);
